### ISSUE TITLE
PATH in https://github.com/VIDA-NYU/bdi-kit/blob/devel/examples/column_and_value_mapping.py

### ISSUE THREAD

**Issue by julianafreire** [VIDA-NYU/bdi-kit#29]
In
os.environ['BDIKIT_MODEL_PATH'] = '/Users/rlopez/Downloads/model_20_1.pt'

Should this be placed in the bdi repo and be accessed here using a relative path? e.g., ./model_20_1.pt

**Comment by roquelopez** [comment]
@julianafreire `model_20_1.pt` is a large file for GitHub (~500MB). We provide a link to download that model in the installation instructions and the user should add the path to this file in  `os.environ['BDIKIT_MODEL_PATH']` (this is a temporal solution). We could add it to the repo using [GitHub LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage), but it will not solve the problem when we publish this to PyPI where the limit is 60MB per file.  I think the best solution is to have a method `bdikit.download_resources()` similar to [nltk.download()](https://www.nltk.org/api/nltk.downloader.html), I proposed it in https://github.com/VIDA-NYU/bdi-kit/issues/24.

**Comment by roquelopez** [comment]
Fixed by https://github.com/VIDA-NYU/bdi-kit/pull/34.
